<link rel="stylesheet" href="{{ asset('print/buttons.print.js')}}">
<link rel="stylesheet" href="{{ asset('print/buttons.bootstrap4.css')}}">
<link rel="stylesheet" href="{{ asset('print/buttons.bootstrap4.css')}}">
<link rel="stylesheet" href="{{ asset('print/buttons.min.js')}}">
<link rel="stylesheet" href="{{ asset('print/dataTables.bootstrap.js')}}">
<link rel="stylesheet" href="{{ asset('print/dataTables.bootstrap.min.js')}}">
<link rel="stylesheet" href="{{ asset('print/dataTables.css')}}">
<link rel="stylesheet" href="{{ asset('print/dataTables.js')}}">
<link rel="stylesheet" href="{{ asset('print/dataTables.min.js')}}">
<link rel="stylesheet" href="{{ asset('print/dataTables.js')}}">
<link rel="stylesheet" href="{{ asset('print/jquery.dataTables.js')}}">
<link rel="stylesheet" href="{{ asset('print/jquery.dataTables.min.js')}}">
<link rel="stylesheet" href="{{ asset('print/jQuery.js')}}">
